config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#home'

  devise_for :job_offerers, controllers: {
    sessions: 'job_offerers/sessions',
    passwords: 'job_offerers/passwords',
    registrations: 'job_offerers/registrations',
    confirmations: 'job_offerers/confirmations'
  }

  devise_scope :job_offerer do
    get 'confirm_email', to: 'job_offerers/registrations#confirm_email'
    post 'job_offerers/guest_sign_in', to: 'job_offerers/sessions#guest'
  end

  scope module: :job_offerers do
    resources :job_offerers, only: %i[index show destroy], controller: :profiles do
      resource :profile, except: %i[show destroy]
    end
  end

  devise_for :job_seekers, controllers: {
    sessions: 'job_seekers/sessions',
    passwords: 'job_seekers/passwords',
    registrations: 'job_seekers/registrations',
    confirmations: 'job_seekers/confirmations'
  }

  devise_scope :job_seeker do
    get 'confirm_email', to: 'job_seekers/registrations#confirm_email'
    post 'job_seekers/guest_sign_in', to: 'job_seekers/sessions#guest'
  end

  scope module: :job_seekers do
    resources :job_seekers, only: %i[index show destroy], controller: :profiles do
      resource :profile, except: %i[show destroy]
      resource :resume, except: %i[index show]
    end
  end

  resources :rooms, only: %i[index show create] do
    resources :entries, only: :destroy
  end

  resources :job_postings do
    resource :bookmark, only: %i[create destroy]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/job_offerer.rb
# frozen_string_literal: true

class JobOfferer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable

  has_one :profile, class_name: 'JobOffererProfile', dependent: :destroy
  has_many :job_postings, dependent: :destroy
  has_many :messages, -> { where('job_seeker_id is NULL') }, dependent: :nullify
  has_many :entries, dependent: :nullify
  has_many :rooms, through: :entries

  def leave(entry)
    entry.update(job_offerer_id: nil)
  end
end

app/controllers/job_offerers/confirmations_controller.rb
# frozen_string_literal: true

class JobOfferers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  def after_confirmation_path_for(_resource_name, resource)
    # super(resource_name, resource)
    sign_in(resource)
    if current_job_offerer.profile.blank?
      flash[:notice] = 'メールアドレスが認証されました。続いてプロフィールを登録してください'
      new_job_offerer_profile_path(resource)
    else
      flash[:notice] = 'メールアドレスが認証されました'
      job_offerer_path(resource)
    end
  end
end

app/controllers/job_offerers/job_postings_controller.rb
class JobOfferers::JobPostingsController < ApplicationController
  include Common

  before_action :authenticate_job_offerer!, except: %i[index show]
  before_action :require_profile, except: %i[index show]
  before_action :posting_requires_correct_user, only: %i[edit update destroy]

  def index
    popular_tags
    @job_postings = searched_postings.page(params[:page])
  end

  def show
    @job_posting = JobPosting.find(params[:id])
  end

  def new
    @job_posting = current_job_offerer.job_postings.build
  end

  def create
    @job_posting = current_job_offerer.job_postings.build(posting_params)
    if @job_posting.save
      redirect_to job_postings_path, notice: '求人を投稿しました'
    else
      render 'new', alert: '求人の投稿に失敗しました'
    end
  end

  def edit
    @job_posting = JobPosting.find(params[:id])
  end

  def update
    @job_posting = JobPosting.find(params[:id])
    if @job_posting.update_attributes(posting_params)
      redirect_to @job_posting, notice: '求人情報を更新しました'
    else
      render 'edit', alert: '求人情報の更新に失敗しました'
    end
  end

  def destroy
    @job_posting = JobPosting.find(params[:id])
    @job_posting.destroy
    flash[:notice] = '求人を削除しました'
    redirect_to job_postings_path
  end

  private

  def posting_params
    params.require(:job_posting).permit(
      :header,
      :title,
      :content,
      :tag_list
    )
  end

  def posting_requires_correct_user
    @job_posting = JobPosting.find(params[:id])
    return unless @job_posting.job_offerer != current_job_offerer

    redirect_back(fallback_location: root_path, alert: '権限がありません')
  end

  def searched_postings
    @q = JobPosting.ransack(params[:q])
    if params[:tag_name]
      JobPosting.tagged_with(params[:tag_name].to_s).recently
    else
      @q.result(distinct: true).recently
    end
  end
end

app/controllers/job_offerers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class JobOfferers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/job_offerers/passwords_controller.rb
# frozen_string_literal: true

class JobOfferers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/job_offerers/profiles_controller.rb
# frozen_string_literal: true

class JobOfferers::ProfilesController < ApplicationController
  include Common

  before_action :authenticate_job_offerer!, except: %i[index show destroy]
  before_action :profile_exists_already, only: %i[new create]
  before_action :require_correct_user, only: %i[edit update]
  before_action :require_admin, only: %i[destroy]
  before_action :check_guest, only: %i[edit update]

  def index
    popular_tags
    @profiles = searched(JobOffererProfile).page(params[:page])
  end

  def show
    @job_offerer = JobOfferer.find(params[:id])
    @profile = @job_offerer.profile
    confirm_profile
  end

  def new
    @profile = current_job_offerer.build_profile
  end

  def create
    @profile = current_job_offerer.build_profile(profile_params)
    if @profile.save
      redirect_to root_url, notice: 'プロフィール設定が完了しました'
    else
      render 'new', alert: 'プロフィール設定に失敗しました'
    end
  end

  def edit
    @profile = JobOffererProfile.find_by(job_offerer_id: params[:job_offerer_id])
  end

  def update
    @profile = JobOffererProfile.find_by(job_offerer_id: params[:job_offerer_id])
    if @profile.update_attributes(profile_params)
      redirect_to @profile.job_offerer, notice: 'プロフィールの更新に成功しました'
    else
      render 'edit', alert: 'プロフィールの更新に失敗しました'
    end
  end

  def destroy
    @job_offerer = JobOfferer.find(params[:id])
    @job_offerer.destroy
    redirect_to job_offerers_path, notice: '求人者を削除しました。'
  end

  private

  def profile_params
    params.require(:job_offerer_profile).permit(
      :first_name, :last_name,
      :first_name_furigana,
      :last_name_furigana,
      :bio,
      :avatar,
      :tag_list
    )
  end

  def check_guest
    @profile = JobOffererProfile.find_by(job_offerer_id: params[:job_offerer_id])
    return unless @profile.job_offerer.email == 'test_offerer@joblink.com'

    redirect_back(fallback_location: root_path, alert: 'ゲストユーザーのプロフィールは変更できません')
  end
end

app/controllers/job_offerers/registrations_controller.rb
# frozen_string_literal: true

class JobOfferers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :check_guest, only: %i[update destroy]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  def destroy
    if resource == current_user && current_user.admin?
      redirect_back(fallback_location: root_path, alert: '管理者は削除できません')
    else
      super
    end
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  def confirm_email
    flash.delete(:notice) if flash[:notice].present?
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(_resource)
    # super(resource)
    confirm_email_path
  end

  def check_guest
    return unless resource.email == 'test_offerer@joblink.com'

    redirect_back(fallback_location: root_path, alert: 'ゲストユーザーは削除・変更できません')
  end
end

app/controllers/job_offerers/sessions_controller.rb
# frozen_string_literal: true

class JobOfferers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def guest
    job_offerer = JobOfferer.find_by(email: 'test_offerer@joblink.com')
    sign_in(job_offerer)
    redirect_to root_url, notice: 'ゲストユーザーとしてログインしました'
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/job_offerers/unlocks_controller.rb
# frozen_string_literal: true

class JobOfferers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/job_seekers/profiles_controller.rb
# frozen_string_literal: true

class JobSeekers::ProfilesController < ApplicationController
  include Common

  before_action :authenticate_job_seeker!, except: %i[index show destroy]
  before_action :profile_exists_already, only: %i[new create]
  before_action :require_correct_user, only: %i[edit update]
  before_action :require_admin, only: %i[destroy]
  before_action :check_guest, only: %i[edit update]

  def index
    popular_tags
    @profiles = searched(JobSeekerProfile).page(params[:page])
  end

  def show
    @job_seeker = JobSeeker.find(params[:id])
    @profile = @job_seeker.profile
    confirm_profile
  end

  def new
    @profile = current_job_seeker.build_profile
  end

  def create
    @profile = current_job_seeker.build_profile(profile_params)
    if @profile.save
      redirect_to root_url, notice: 'プロフィール設定が完了しました'
    else
      render 'new', alert: 'プロフィール設定に失敗しました'
    end
  end

  def edit
    @profile = JobSeekerProfile.find_by(job_seeker_id: params[:job_seeker_id])
  end

  def update
    @profile = JobSeekerProfile.find_by(job_seeker_id: params[:job_seeker_id])
    if @profile.update_attributes(profile_params)
      redirect_to @profile.job_seeker, notice: 'プロフィールの更新に成功しました'
    else
      render 'edit', alert: 'プロフィールの更新に失敗しました'
    end
  end

  def destroy
    @job_seeker = JobSeeker.find(params[:id])
    @job_seeker.destroy
    redirect_to job_seekers_path, notice: '求職者を削除しました。'
  end

  private

  def profile_params
    params.require(:job_seeker_profile).permit(
      :first_name, :last_name,
      :first_name_furigana,
      :last_name_furigana,
      :bio,
      :avatar,
      :tag_list
    )
  end

  def check_guest
    @profile = JobSeekerProfile.find_by(job_seeker_id: params[:job_seeker_id])
    return unless @profile.job_seeker.email == 'test_seeker@joblink.com'

    redirect_back(fallback_location: root_path, alert: 'ゲストユーザーのプロフィールは変更できません')
  end
end

app/helpers/job_offerers/profiles_helper.rb
# frozen_string_literal: true

module JobOfferers::ProfilesHelper
end

app/helpers/job_seekers/profiles_helper.rb
# frozen_string_literal: true

module JobSeekers::ProfilesHelper
end

app/views/job_offerers/profiles/_form.html.slim
= render 'shared/error_messages', model: f.object
.row.valign-wrapper
  .col.s6
    .center
      - if @profile.avatar.attached?
        = image_tag @profile.avatar.variant(resize_to_fill: [200,200]), id: :avatar_prev, class: 'circle responsive-img'
      - else
        = image_tag '/default_avatar.png', id: :avatar_prev, class: 'circle responsive-img', size: '200x200'
  .file-field.input-field.col.s6
    .btn 
      span アバター
      = f.file_field :avatar, id: :avatar_img
    .file-path-wrapper
      = f.text_field :file_path, class: 'file-path validate'
.row
  .input-field.col.s6
    = f.label :last_name
    = f.text_field :last_name
    span.helper-text
      | *必須項目
  .input-field.col.s6
    = f.label :first_name
    = f.text_field :first_name
    span.helper-text
      | *必須項目
.row
  .input-field.col.s6
    = f.label :last_name_furigana
    = f.text_field :last_name_furigana
    span.helper-text
      | *必須項目
  .input-field.col.s6
    = f.label :first_name_furigana
    = f.text_field :first_name_furigana
    span.helper-text
      | *必須項目
.row
  .input-field.col.s12
    = f.label :bio
    = f.text_area :bio, class: 'materialize-textarea character_limit', data: {length: '160'}
.row
  .input-field.col.s12
    = f.label :tag_list
    = f.text_field :tag_list, value: @profile.tag_list.join(',' + ' ')
    span.helper-text
      | *コンマまたはスペース区切りで複数入力可能

app/views/job_offerers/profiles/edit.html.slim
h3
  | プロフィールの編集
= form_with model: @profile, url: job_offerer_profile_path, local: true do |f|
  = render 'form', f: f
  .row
    .actions
      = f.submit '更新', class: 'btn right'

app/views/job_offerers/profiles/index.html.slim
h4
  | 求人者
.row
  = search_form_for @q, url: job_offerers_path do |f|
    .container
      .input-field.col.s10
        = f.text_field :profile_cont, placeholder: 'キーワードで求人者を検索'
      .input-field.col.s2
        = button_tag class: 'btn-flat'
          i.material-icons search
.row
  .container
    | 人気のタグ: 
    - @tags.each do |tag|
      = link_to tag, job_offerers_path(tag_name: tag.name), class: 'chip'
.divider
.section
  = render 'shared/user_criteria'
  - if @profiles.present?
    .collection
      - @profiles.each do |profile|
        = link_to(job_offerer_path(profile.job_offerer), class: 'collection-item avatar black-text') do
          - if profile.avatar.attached?
            = image_tag profile.shaped_avatar, class: 'circle'
          - else 
            = image_tag '/default_avatar.png', class: 'circle'
          span.title
            = profile.full_name
          p
            = profile.bio
          - profile.tag_list.each do |tag|
            span.chip
              = tag
  - else
    .row
      p お探しの条件に該当する結果が見つかりませんでした。
  = paginate @profiles

app/views/job_offerers/profiles/new.html.slim
h3
  | プロフィールの登録
= form_with model: @profile, url: job_offerer_profile_path, local: true do |f|
  = render 'form', f: f
  .row
    .actions
      = f.submit '登録', class: 'btn right'

app/views/job_offerers/profiles/show.html.slim
.section
  .row
    - if @profile.avatar.attached?
      = image_tag @profile.shaped_avatar, class: 'circle responsive-img'
    - else
      = image_tag '/default_avatar.png', class: 'circle responsive-img', size: '200x200'
  .col.s2.offset-s2.right
    - if correct_user?
      = link_to '編集', edit_job_offerer_profile_path(@job_offerer), class: 'btn'
    - if job_seeker_signed_in?
      - if current_job_seeker.rooms.find_by(id: @job_offerer.rooms)
        =< link_to 'メッセージ', room_path(current_job_seeker.rooms.find_by(id: @job_offerer.rooms)), class: 'btn'
      - else
        =< link_to 'メッセージ', rooms_path(entry: {job_seeker_id: current_job_seeker, job_offerer_id: @job_offerer}), method: :post, class: 'btn'
  .col.s10
    h4
      ruby
        rb = @profile.full_name
        rt = @profile.full_name_furigana
      - if correct_user? && @job_offerer.admin?
        i.material-icons check_circle
    p
      - if @job_offerer.admin?
        | @administrator
      - else
        = @profile.job_offerer.email
  h6
    = @profile.bio
  .row
    - @profile.tag_list.each do |tag|
      = link_to tag, job_offerers_path(tag_name: tag), class: 'chip'
.row
  .col.s12
    ul.tabs
      li.tab.col.s12 
        = link_to "投稿した求人", "#job_postings"
  #job_postings.col.s12
    - if @job_offerer.job_postings.present?  
      = render 'job_postings/list', job_postings: @job_offerer.job_postings
    - else
      .section
        p 求人を投稿していません。
        - if correct_user?
          = link_to '求人を投稿する', new_job_posting_path
- if user_signed_in?
  .section
    - if correct_user?
      .row
        = link_to 'アカウント設定', edit_job_offerer_registration_path
    - if current_user.admin? && @job_offerer != current_user
      .row
        = link_to 'この求人者を削除', job_offerer_path(@job_offerer), data: { confirm: "この求人者を削除しますか?" }, method: :delete
- if job_offerer_signed_in? && correct_user?
  = render 'shared/post_button'