config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#home'

  devise_for :job_offerers, controllers: {
    sessions: 'job_offerers/sessions',
    passwords: 'job_offerers/passwords',
    registrations: 'job_offerers/registrations',
    confirmations: 'job_offerers/confirmations'
  }

  devise_scope :job_offerer do
    get 'confirm_email', to: 'job_offerers/registrations#confirm_email'
    post 'job_offerers/guest_sign_in', to: 'job_offerers/sessions#guest'
  end

  scope module: :job_offerers do
    resources :job_offerers, only: %i[index show destroy], controller: :profiles do
      resource :profile, except: %i[show destroy]
    end
  end

  devise_for :job_seekers, controllers: {
    sessions: 'job_seekers/sessions',
    passwords: 'job_seekers/passwords',
    registrations: 'job_seekers/registrations',
    confirmations: 'job_seekers/confirmations'
  }

  devise_scope :job_seeker do
    get 'confirm_email', to: 'job_seekers/registrations#confirm_email'
    post 'job_seekers/guest_sign_in', to: 'job_seekers/sessions#guest'
  end

  scope module: :job_seekers do
    resources :job_seekers, only: %i[index show destroy], controller: :profiles do
      resource :profile, except: %i[show destroy]
      resource :resume, except: %i[index show]
    end
  end

  resources :rooms, only: %i[index show create] do
    resources :entries, only: :destroy
  end

  resources :job_postings do
    resource :bookmark, only: %i[create destroy]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_action_text_help.html.slim
li
  .collapsible-header
    i.material-icons mode_edit
    | エディタの使い方
  .collapsible-body
    p 
      | このエディタは書式や画像の挿入を便利にするものです。
    p 
      | 各機能の説明(左から)
      ul
        li 「Bold」 - 太字
        li 「Italic」 - 斜体
        li 「Strikethrough」 - 打ち消し線
        li 「Link」 - URLリンクの挿入
      br
      ul
        li 「Heading」 - 見出し
        li 「Quote」 - 引用
        li 「Code」 - コードブロック
        li 「Bullets」 - 箇条書き
        li 「Numbers」 - 番号リスト
        li 「Decrease Level」 - インデントを減らす
        li 「Increase Level」 - インデントを増やす
      br
      ul
        li 「Attach Files」 - 画像の挿入<br>(画像はドラッグ&ドロップで追加することもできます)

app/views/shared/_error_messages.html.slim
- if model.errors.any?
  .row
    .card-panel.red.white-text
      .valign-wrapper
        .col.s2
          .center  
            i.material-icons.medium error_outline
        .col.s10
          ul
            - model.errors.full_messages.each do |message|
              li = message

app/views/shared/_post_button.html.slim
.fixed-action-btn
  = link_to new_job_posting_path, class: 'btn-floating btn-large' do
    i.large.material-icons create

app/views/shared/_sidenav.html.slim
ul#slide-out.sidenav
  - if job_offerer_signed_in?
    li = link_to job_offerer_path(current_job_offerer)
      i.material-icons account_circle
      | マイページ
  - elsif job_seeker_signed_in?
    li = link_to job_seeker_path(current_job_seeker)
      i.material-icons account_circle
      | マイページ
  li = link_to job_postings_path
    i.material-icons description
    | 求人一覧
  li = link_to job_offerers_path
    i.material-icons people
    | 求人者一覧
  li = link_to job_seekers_path
    i.material-icons people_outline
    | 求職者一覧
  - if user_signed_in?
    li = link_to rooms_path
      i.material-icons chat
      | トーク
    li.divider
    - if job_offerer_signed_in?
      li = link_to destroy_job_offerer_session_path, method: :delete, data: {confirm: 'ログアウトしますか？'}
        i.material-icons exit_to_app
        | ログアウト
    -elsif job_seeker_signed_in?
      li = link_to destroy_job_seeker_session_path, method: :delete, data: {confirm: 'ログアウトしますか？'}
        i.material-icons exit_to_app
        | ログアウト
  - else
    li.divider
    li.no-padding
      ul.collapsible.collapsible-accodion
        li
          a.collapsible-header
            i.material-icons arrow_drop_down
            | 求人者の方はこちら
          .collapsible-body
            ul
              li = link_to "アカウント登録", new_job_offerer_registration_path
              li = link_to "ログイン", new_job_offerer_session_path
        li
          a.collapsible-header
            i.material-icons arrow_drop_down
            | 求職者の方はこちら
          .collapsible-body
            ul
              li = link_to "アカウント登録", new_job_seeker_registration_path
              li = link_to "ログイン", new_job_seeker_session_path

app/views/shared/_toast.html.slim
- unless flash.empty?
  - flash.each do |message_type, message|
    - next if message_type == 'timedout'
    javascript:
      M.toast({html: "#{message}"})

app/views/shared/_user_criteria.html.slim
.row
  - if params[:q].present? && params[:q][:profile_cont].present?
    = params[:q][:profile_cont]
    |  の検索結果:
  - elsif params[:tag_name].present?
    = params[:tag_name]
    |  の検索結果:
  - else
    | 全件表示: