config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#home'

  devise_for :job_offerers, controllers: {
    sessions: 'job_offerers/sessions',
    passwords: 'job_offerers/passwords',
    registrations: 'job_offerers/registrations',
    confirmations: 'job_offerers/confirmations'
  }

  devise_scope :job_offerer do
    get 'confirm_email', to: 'job_offerers/registrations#confirm_email'
    post 'job_offerers/guest_sign_in', to: 'job_offerers/sessions#guest'
  end

  scope module: :job_offerers do
    resources :job_offerers, only: %i[index show destroy], controller: :profiles do
      resource :profile, except: %i[show destroy]
    end
  end

  devise_for :job_seekers, controllers: {
    sessions: 'job_seekers/sessions',
    passwords: 'job_seekers/passwords',
    registrations: 'job_seekers/registrations',
    confirmations: 'job_seekers/confirmations'
  }

  devise_scope :job_seeker do
    get 'confirm_email', to: 'job_seekers/registrations#confirm_email'
    post 'job_seekers/guest_sign_in', to: 'job_seekers/sessions#guest'
  end

  scope module: :job_seekers do
    resources :job_seekers, only: %i[index show destroy], controller: :profiles do
      resource :profile, except: %i[show destroy]
      resource :resume, except: %i[index show]
    end
  end

  resources :rooms, only: %i[index show create] do
    resources :entries, only: :destroy
  end

  resources :job_postings do
    resource :bookmark, only: %i[create destroy]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/job_posting.rb
# frozen_string_literal: true

class JobPosting < ApplicationRecord
  belongs_to :job_offerer
  has_many :bookmarks, dependent: :destroy
  has_many :job_seekers, through: :bookmarks
  has_one_attached :header
  has_rich_text :content

  validate :header, :validate_header
  validates :title, :content, presence: true
  validates :title, length: { maximum: 40 }

  acts_as_taggable

  scope :recently, -> { order(updated_at: :desc) }
  scope :popular, lambda {
    find(
      Bookmark.group(:job_posting_id)
              .order('count(job_posting_id) desc')
              .limit(5)
              .pluck(:job_posting_id)
    )
  }

  def bookmarked_by(job_seeker)
    bookmarks.find_by(job_seeker_id: job_seeker)
  end

  def shaped_header
    header.variant(resize_to_fill: [1000, 500]).processed
  end

  def thumbnail
    header.variant(resize_to_fill: [1000, 400]).processed
  end

  private

  def validate_header
    return unless header.attached?

    if !header.content_type.in?(%(image/jpeg image/jpg image/png))
      self.header = nil
      errors.add(:header, 'には、.jpeg, .jpg, .png のみ添付できます。')
    elsif header.blob.byte_size > 10.megabytes
      self.header = nil
      errors.add(:header, 'は10MB以下のみ添付できます。')
    end
  end
end

app/controllers/job_offerers/job_postings_controller.rb
class JobOfferers::JobPostingsController < ApplicationController
  include Common

  before_action :authenticate_job_offerer!, except: %i[index show]
  before_action :require_profile, except: %i[index show]
  before_action :posting_requires_correct_user, only: %i[edit update destroy]

  def index
    popular_tags
    @job_postings = searched_postings.page(params[:page])
  end

  def show
    @job_posting = JobPosting.find(params[:id])
  end

  def new
    @job_posting = current_job_offerer.job_postings.build
  end

  def create
    @job_posting = current_job_offerer.job_postings.build(posting_params)
    if @job_posting.save
      redirect_to job_postings_path, notice: '求人を投稿しました'
    else
      render 'new', alert: '求人の投稿に失敗しました'
    end
  end

  def edit
    @job_posting = JobPosting.find(params[:id])
  end

  def update
    @job_posting = JobPosting.find(params[:id])
    if @job_posting.update_attributes(posting_params)
      redirect_to @job_posting, notice: '求人情報を更新しました'
    else
      render 'edit', alert: '求人情報の更新に失敗しました'
    end
  end

  def destroy
    @job_posting = JobPosting.find(params[:id])
    @job_posting.destroy
    flash[:notice] = '求人を削除しました'
    redirect_to job_postings_path
  end

  private

  def posting_params
    params.require(:job_posting).permit(
      :header,
      :title,
      :content,
      :tag_list
    )
  end

  def posting_requires_correct_user
    @job_posting = JobPosting.find(params[:id])
    return unless @job_posting.job_offerer != current_job_offerer

    redirect_back(fallback_location: root_path, alert: '権限がありません')
  end

  def searched_postings
    @q = JobPosting.ransack(params[:q])
    if params[:tag_name]
      JobPosting.tagged_with(params[:tag_name].to_s).recently
    else
      @q.result(distinct: true).recently
    end
  end
end

app/controllers/job_postings_controller.rb
# frozen_string_literal: true

class JobPostingsController < ApplicationController
  include Common

  before_action :authenticate_job_offerer!, except: %i[index show]
  before_action :require_profile, except: %i[index show]
  before_action :posting_requires_correct_user, only: %i[edit update destroy]

  def index
    popular_tags
    @job_postings = searched_postings.page(params[:page]).per(10)
  end

  def show
    @job_posting = JobPosting.find(params[:id])
  end

  def new
    @job_posting = current_job_offerer.job_postings.build
  end

  def create
    @job_posting = current_job_offerer.job_postings.build(posting_params)
    if @job_posting.save
      redirect_to job_postings_path, notice: '求人を投稿しました'
    else
      render 'new', alert: '求人の投稿に失敗しました'
    end
  end

  def edit
    @job_posting = JobPosting.find(params[:id])
  end

  def update
    @job_posting = JobPosting.find(params[:id])
    if @job_posting.update_attributes(posting_params)
      redirect_to @job_posting, notice: '求人情報を更新しました'
    else
      render 'edit', alert: '求人情報の更新に失敗しました'
    end
  end

  def destroy
    @job_posting = JobPosting.find(params[:id])
    @job_posting.destroy
    flash[:notice] = '求人を削除しました'
    redirect_to job_postings_path
  end

  private

  def posting_params
    params.require(:job_posting).permit(
      :header,
      :title,
      :content,
      :tag_list
    )
  end

  def posting_requires_correct_user
    @job_posting = JobPosting.find(params[:id])
    return unless @job_posting.job_offerer != current_job_offerer

    redirect_back(fallback_location: root_path, alert: '権限がありません')
  end

  def searched_postings
    @q = JobPosting.ransack(params[:q])
    if params[:tag_name]
      JobPosting.tagged_with(params[:tag_name].to_s).recently
    else
      @q.result(distinct: true).recently
    end
  end
end

app/helpers/job_postings_helper.rb
# frozen_string_literal: true

module JobPostingsHelper
end

app/views/job_postings/_form.html.slim
= render 'shared/error_messages', model: f.object
.row
  .center
    - if @job_posting.header.attached?
      = image_tag @job_posting.shaped_header, id: :header_prev, class: 'responsive-img'
    - else
      = image_tag '/no_image.png', id: :header_prev, class:'responsive-img', size: '500x500'
  .file-field.input-field.col.s6
    .btn 
      span ヘッダー
      = f.file_field :header, id: :header_img
    .file-path-wrapper
      = f.text_field :file_path, class: 'file-path validate'
    span.helper-text
      | *画像を選択するとプレビューを表示します
.row
  .input-field
    = f.label :title
    = f.text_field :title
.row
  .input-field 
    = f.label :tag_list
    = f.text_field :tag_list, value: @job_posting.tag_list.join(',' + ' ')
    span.helper-text
      | *コンマまたはスペース区切りで複数入力可能
.row
  p 文章や画像を使って求人票を作成しましょう。
  .input-field
    = f.rich_text_area :content

app/views/job_postings/_help.html.slim
.section
  ul.collapsible
    li
      .collapsible-header
        i.material-icons help_outline
        | 何を書けばいいかわかりませんか?
      .collapsible-body
        p
          | 求人は後から書き直すこともできます。<br>
          | 情報量が少なくても、まずは書いて投稿してみましょう。<br>
          | あなたは複数の求人を投稿できますので、募集しているポジションごとに分けて投稿するのも良いでしょう。<br>
          | どうしても書くことがわからないなら、以下を参考にしてみてください。
        p 
          | あった方がいい項目
          ol
            li なにをやっているのか - 事業概要
            li なぜやっているのか - 行動理念
            li どんな人に来て欲しいのか - 求める人物像
            li なにができて欲しいか - 必要なスキル
        p
          | なくてもよいが、あると好ましい項目
          ol
            li 会社名
            li 雇用条件
        p
          | 上記の他にも、自由に項目を作ってみてください。<br>
          | ベストマッチを生み出せる求人を書きましょう。
    = render 'shared/action_text_help'

app/views/job_postings/_list.html.slim
- job_postings.each do |job_posting|
  .card
    = link_to(job_posting_path(job_posting)) do
      .card-image
        - if job_posting.header.attached?
          = image_tag job_posting.thumbnail, class: 'responsive-img'
        - else
          = image_tag '/no_image.png', size: '1000x400'
        .card-title
          = render 'bookmarks/bookmark', job_posting: job_posting
    = link_to(job_posting_path(job_posting)) do
      .card-content
        h5.black-text
          = job_posting.title
        - job_posting.tag_list.each do |tag|
          span.chip
            = tag

app/views/job_postings/edit.html.slim
h3
  | 求人情報の編集
= form_with model: @job_posting, local: true do |f|
  = render 'form', f: f
  .row
    .actions
      = f.submit '更新', class: 'btn right'
= render 'help'

app/views/job_postings/index.html.slim
h4
  | 求人
.row
  = search_form_for @q do |f|
    .container
      .input-field.col.s10
        = f.text_field :title_cont, placeholder: 'キーワードで求人を検索'
      .input-field.col.s2
        = button_tag class: 'btn-flat'
          i.material-icons search
.row
  .container
    | 人気のタグ: 
    - @tags.each do |tag|
      = link_to tag, job_postings_path(tag_name: tag.name), class: 'chip'
.divider
.section
  .row
    - if params[:q].present? && params[:q][:title_cont].present?
      = params[:q][:title_cont]
      |  の検索結果:
    - elsif params[:tag_name].present?
      = params[:tag_name]
      |  の検索結果:
    - else
      | 全件表示:
  - if @job_postings.present?
    = render 'list', job_postings: @job_postings
  - else
    .row
      p お探しの条件に該当する結果が見つかりませんでした。
  = paginate @job_postings
- if job_offerer_signed_in?
  = render 'shared/post_button'

app/views/job_postings/new.html.slim
h3
  | 新規求人
= form_with model: @job_posting, local: true do |f|
  = render 'form', f: f
  .row
    .actions
      = f.submit '投稿', class: 'btn right'
= render 'help'

app/views/job_postings/show.html.slim
.section
  .row
    .center
      - if @job_posting.header.attached?
        = image_tag @job_posting.shaped_header, class: 'responsive-img'
      - else
        = image_tag '/no_image.png', class: 'responsive-img'
  .row
    h4
      = @job_posting.title
  .row.valign-wrapper
    .col.s10
      .valign-wrapper
        = link_to job_offerer_path(@job_posting.job_offerer) do
          - if @job_posting.job_offerer.profile.avatar.attached?
            = image_tag @job_posting.job_offerer.profile.avatar.variant(resize_to_fill: [50, 50]), class: 'circle'
          - else
            = image_tag '/default_avatar.png', class: 'circle', size: '50x50'
        | &nbsp
        = link_to @job_posting.job_offerer.profile.full_name, job_offerer_path(@job_posting.job_offerer), class: 'black-text'
    .col.s2
      .right
        = render 'bookmarks/bookmark', job_posting: @job_posting
  .row
    - @job_posting.tag_list.each do |tag|
      = link_to tag, job_postings_path(tag_name: tag), class: 'chip'
  .row
    p
      == @job_posting.content
.section
  - if @job_posting.job_offerer == current_job_offerer
    .row
      .right
        = link_to '編集', edit_job_posting_path, class: 'btn'
        =< link_to '削除', job_posting_path, data: { confirm: "この求人を削除しますか?" }, method: :delete, class: 'btn'